site: Jasmin Codes
url: www.jasmin.codes
author: Jasmin Hudacsek
author:
  name: Jasmin Hudacsek
  email: jasmin@hudacsek.com
  url:
  avatar:
title: Jasmin Codes
description: Jasmin Hudacsek's Personal Website
logo:
image:
social:
  name: Jasmin Hudacsek
  links:
    - https://twitter.com/j_sm_n
    - https://github.com/j-sm-n

permalink: pretty

baseurl:             ""

include:
  - _redirects

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  projects:
    output: true
    permalink: /projects/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

  - scope:
      path: "assets/images"
    values:
      image: true
